language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -e .[dev]
script:
  - python3 -m unittest discover .
  - mypy nix_review
  - flake8
  # broken on 3.7 atm (https://github.com/ambv/black/issues/425)
  - |
    [[ $TRAVIS_PYTHON_VERSION == 3.7-dev ]] || black --check .
